In [2]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle

In [3]:
path='/home/drallab/datamining/Yelp_Sentiment_Analysis-master/data/review_subset.csv'
data = pd.read_csv(path)
data.head()
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4781551 entries, 0 to 4781550
Data columns (total 6 columns):
business_id    object
date           object
review_id      object
stars          float64
text           object
user_id        object
dtypes: float64(1), object(5)
memory usage: 218.9+ MB


In [4]:
df1 = data.iloc[:,3:5]

In [5]:
df1.info()
df1 = df1[(df1.stars == 5) | (df1.stars == 1)]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4781551 entries, 0 to 4781550
Data columns (total 2 columns):
stars    float64
text     object
dtypes: float64(1), object(1)
memory usage: 73.0+ MB


In [6]:
df1 = shuffle(df1)

In [7]:
df1.dropna(inplace=True)

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3026342 entries, 2547031 to 4010462
Data columns (total 2 columns):
stars    float64
text     object
dtypes: float64(1), object(1)
memory usage: 69.3+ MB


In [9]:
df1.isnull().values.any()

False

In [10]:
df1.head()

stars                                               text
2547031    5.0  Great sushi! Even better staff. It's a great p...
4440921    5.0  Madness Cup is conveniently by the Box Office ...
3103894    1.0  Extremely flavorless and hard to eat chicken w...
2388380    1.0  In a strange set of circumstances, this Pizza ...
2000918    5.0  This was my second time to Osaka and I (we) re...

In [11]:
X_data = df1['text']
y_data = df1['stars']   

In [12]:
X_data.shape


(3026342,)

In [13]:
y_data.shape

(3026342,)

In [14]:
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X_data,y_data,test_size =0.3,random_state=42)
print (X_train.shape)
print (X_test.shape)
print (y_train.shape)
print (y_test.shape)

/software/anaconda3/5.1.0/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


(2118439,)
(907903,)
(2118439,)
(907903,)


In [15]:
#CountVectorizer shall be used to work on text data
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)
X_train_dtm


<2118439x342158 sparse matrix of type '<class 'numpy.int64'>'
	with 136958109 stored elements in Compressed Sparse Row format>

In [16]:
#Vectorize Test data
X_test_dtm = vect.transform(X_test)


In [16]:
#Encode 1 and 5 rating
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
y_train=lb.fit_transform(y_train)
y_test=lb.fit_transform(y_test)

In [17]:
#using GridsearchCV for parameter selection and tuning.

from sklearn.linear_model import LogisticRegression
from sklearn.grid_search import GridSearchCV


grid = GridSearchCV(LogisticRegression(),param_grid={'C':np.arange(1,20,0.2),'penalty':['l1','l2']},cv=10)
grid.fit(X_train_dtm,y_train)

/software/anaconda3/5.1.0/lib/python3.6/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


GridSearchCV(cv=10, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'C': array([ 1. ,  1.2, ..., 19.6, 19.8]), 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [18]:
# predict 
grid.predict(X_test_dtm)

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1])

In [19]:
# Best params
grid.best_params_

{'C': 1.0, 'penalty': 'l2'}

In [20]:
#Best Score
grid.best_score_

0.8974358974358975

In [17]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(C=4.19,penalty='l2')
log_reg.fit(X_train_dtm,y_train)

LogisticRegression(C=4.19, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [19]:
#predict
logr_pred = log_reg.predict(X_test_dtm)
print (logr_pred)

[5. 5. 5. ... 5. 5. 5.]


In [20]:
#lets analyse 25 elements of predicted and test y labels , 0 means 1 rating and 1 means 5 rating 
print('Predicted',(logr_pred[:25]))
print('True     ',(y_test[:25]))

Predicted [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 1. 5. 1. 5. 1. 1. 5. 5. 5. 1. 1. 5. 1.
 5.]
True      3555780    5.0
4189475    5.0
491733     5.0
1217858    5.0
397618     5.0
1186835    5.0
3284383    5.0
3245477    5.0
2507024    5.0
4779129    5.0
4644919    5.0
1823679    1.0
1133311    5.0
1901053    1.0
4445984    5.0
2570387    1.0
2320451    1.0
1406279    5.0
2063675    5.0
1148738    5.0
4342600    1.0
2416826    1.0
3030190    5.0
2921277    1.0
340148     5.0
Name: stars, dtype: float64


In [21]:
from sklearn import metrics
print ('accuracy score',metrics.accuracy_score(y_test,logr_pred))

accuracy score 0.9807633634870686


In [22]:
#Lets see the confusion metrix 
conf_matrix=metrics.confusion_matrix(y_test,logr_pred)
print ('confusion matrix \n',conf_matrix)

confusion matrix 
 [[213764   9740]
 [  7725 676674]]


In [23]:
#visualize

pd.crosstab(y_test, logr_pred, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted     1.0     5.0     All
True                             
1.0        213764    9740  223504
5.0          7725  676674  684399
All        221489  686414  907903

In [25]:
#Sensitivity : is the classifier to detecting positive instances , also True Positive Rate" or "Recall"
recall_logr= metrics.recall_score(y_test,logr_pred)
print ('Recall score',recall_logr)

Recall score 0.9564213615863698


In [26]:
#Precision: When a positive value is predicted, how often is the prediction correct?
#How "precise" is the classifier when predicting positive instances?

Precision_logr= metrics.precision_score(y_test,logr_pred)
print('Precision Score', Precision_logr)

Precision Score 0.9651224214295067


In [27]:
#print rating 1 reviews which are falsely callisified as positive i.e rating 5 ,diplay False Postive review comments
X_test[(logr_pred == 1) & (y_test == 0)]

Series([], Name: text, dtype: object)

In [29]:
#print rating 5 reviews which are falsely callisified as negative i.e rating 1,diplay True Negative review comments
X_test[(logr_pred == 0) & (y_test == 1)]

Series([], Name: text, dtype: object)

In [38]:
X_test[880]

"I purchased a used safe on Craigslist.  Not just any safe mind you.  Oh no, I HAD to have the super high security 4000 lb bank safe ... especially at the dirt cheap price it was listed.\n\nLet me say that again - FOUR THOUSAND POUNDS.  Two tons.  About the same as a Toyota Highlander.  5 feet tall, 4 feet wide, and about 35 inches deep.\n\nI spent several days calling around to places to get it moved.  No one wanted to touch this thing.  Then I called The Safe Keeper.\n\nDon (the owner) agreed to do it for $800.  More than I wanted to spend, because I'm a cheapskate.  I finally agreed since no one else would take the job.\n\nI'M GLAD I DID!!\n\nDon and 3 of his guys picked it up from a warehouse near the strip, moved it to my home in Centennial.  They used two pallet jacks, an assortment of wood blocks and chocks, and floor coverings.  Four turns and one 36 inch wide doorway later, they had it placed EXACTLY where I wanted it.  No scuffed walls.  No indentations in the linoleum.  No d

In [30]:
#Lets print classifcation report
class_report = metrics.classification_report(y_test,logr_pred)
print (class_report)

             precision    recall  f1-score   support

        1.0       0.97      0.96      0.96    223504
        5.0       0.99      0.99      0.99    684399

avg / total       0.98      0.98      0.98    907903

